---
- hosts: maas
  user: vagrant
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - language-pack-en-base
          - python-apt
          - python-pycurl
          - ubuntu-cloud-keyring
          - maas
          - maas-dns
          - maas-dhcp
          - snap
    - name: install juju
      command: snap install juju --classic
    - name: create maas admin account
      command: maas init --admin-username cedille --admin-password cedille --admin-email cedille@etsmtl.net
