---
- hosts: all
  user: vagrant
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - language-pack-en-base
          - ubuntu-cloud-keyring
          - python-apt
          - python-pycurl
          - maas-enlist
          - maas-cli

    - name: Update system
      apt: upgrade=dist
    - name: enlist node into maas
      command: maas-enlist --serverurl 192.168.50.99 --interface eth1
